class Utilisateurs extends
{

public $table = "subvention";

public $champs = array(
'S.id',
'S.created_at',
'S.dossier_import',
'S.dossier',
'S.tiers_code_postal_import',
'S.tiers_code_postal',
'S.tiers_ville_import',
'S.tiers_ville',
'S.canton_import',
'S.canton_id',
'S.montant_import',
'S.montant',
'S.status',
'S.status_creation',
'S.commission_id',
'S.tiers_label',
'S.type',
'S.objet_import',
'S.thematique_import',
'S.contact_nom_import',
'S.contact_prenom_import',
'S.contact_civilite_import',
'S.voie_tiers_import',
'S.voie_complement_tiers_import',
'S.politique_import',
'S.mission_import',
'S.action_import',
'S.fonction_import',
'S.objet',
'S.thematique',
'S.contact_nom',
'S.contact_civilite',
'S.civilite2',
'S.voie_tiers',
'S.voie_complement_tiers',
'S.politique',
'S.mission',
'S.action',
'S.contact_fonction',
'S.numero_commission',
'S.numero_commission_import',
'S.contact_nom2_import',
'S.contact_prenom2_import',
'S.contact_nom3_import',
'S.contact_prenom3_import',
'S.contact_fonction_formule',
'S.modified_at',
'S.service',
'S.service_import',
'S.created_by',
'S.politique_action_id',
'S.commune_id',
'S.commune_hors_territoire',
'S.contact_email',
'S.contact_tel',
'S.non_vote'
);
public $champsExternes = array(
'C.label as canton_label',
'CO.label as commission_label',
'CO.commission_date as commission_date',
'PA.politique AS politique_f64',
'PA.action AS action_f64',
'COM.code_postal AS commune_code_postal',
'COM.label AS commune_label'
);

public $champsInsert = array(
'created_at',
'dossier_import',
'dossier',
'tiers_code_postal_import',
'tiers_code_postal',
'tiers_ville_import',
'tiers_ville',
'canton_import',
'canton_id',
'montant_import',
'montant',
'status',
'status_creation',
'commission_id',
'tiers_label',
'type',
'objet_import',
'thematique_import',
'contact_nom_import',
'contact_prenom_import',
'contact_civilite_import',
'voie_tiers_import',
'voie_complement_tiers_import',
'politique_import',
'mission_import',
'action_import',
'fonction_import',
'objet',
'thematique',
'contact_nom',
'contact_civilite',
'civilite2',
'voie_tiers',
'voie_complement_tiers',
'politique',
'mission',
'action',
'contact_fonction',
'numero_commission',
'numero_commission_import',
'contact_nom2_import',
'contact_prenom2_import',
'contact_nom3_import',
'contact_prenom3_import',
'contact_fonction_formule',
'service',
'service_import',
'created_by',
'politique_action_id',
'commune_id',
'commune_hors_territoire',
'contact_email',
'contact_tel',
'non_vote'
);
/**
* @var mixed|void
*/

public function __construct($id = NULL){
parent::setTable($this->table);
parent::__construct($id);
}
