DROP TABLE IF EXISTS PREPARATION;
DROP TABLE IF EXISTS COMMANDE;
DROP TABLE IF EXISTS CONTENU_LOT;
DROP TABLE IF EXISTS LOT;
DROP TABLE IF EXISTS PRODUIT;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS UTILISATEUR;
DROP TABLE IF EXISTS ROLE;
